experiment:
    save_to: /home/atv/Desktop/experiments/yamaha_maxent_irl/semantics
    name: linear_semantics_geometry
    device: cuda
    epochs: 5
    steps_per_epoch: -1
    save_every: 1

algo:
    type: MPPIIRLSpeedmaps
    params:
        mppi_itrs: 10
        batch_size: 12
        reg_coeff: 0.0
        speed_coeff: 0.0
        grad_clip: 1000000.0

dataset:
    type: MaxEntIRLDataset
    params:
        bag_fp: /home/atv/Desktop/datasets/yamaha_maxent_irl/racer_semantics/rosbags_train
        preprocess_fp: /home/atv/Desktop/datasets/yamaha_maxent_irl/racer_semantics/torch_train
        map_features_topic: /local_gridmap
        odom_topic: /integrated_to_init
        image_topic: /multisense/left/image_rect_color
        horizon: 75
        feature_keys:
            - height_low
            - height_mean
            - height_high
            - height_max
            - diff
            - terrain
            - terrain_slope
            - roughness
            - SVD1
            - SVD2
            - SVD3
            - unknown
            - semantic_unknown
            - semantic_label_2 #trail
            - semantic_label_3 #grass
            - semantic_label_4 #low veg
            - semantic_label_5 #high veg
            - semantic_label_6 #obstacle

network:
    type: LinearCostmapSpeedmapEnsemble2
    params:
        ensemble_dim: 16
        activation_type: none
        activation_scale: 1.0
        dropout: 0.0

netopt:
    type: AdamW
    params: {}

cost_function:
    terms:
        - type: CostmapProjection
          weight: 1.0
          params:

        - type: EuclideanDistanceToGoal
          weight: 10.0
          params:

model:
    type: SteerSetpointKBM
    params:
        L: 2.94
        v_target_lim: [2.0, 15.0]
        steer_lim: [-0.5, 0.5]
        steer_rate_lim: 0.5
        v_Kp: 1.0
        w_Kp: 10.0

trajopt:
    type: BatchMPPI
    params: 
        num_samples: 2048
        control_params:
            sys_noise: [5.0, 0.25]
            temperature: 0.05
            use_ou: True
            ou_alpha: 0.9
            ou_scale: 10.0
            d_ou_scale: 2.0

metrics:
