experiment:
    save_to: /home/atv/Desktop/experiments/yamaha_maxent_irl/
    name: cost_swath_point_state_visitations
    device: cuda
    epochs: 10
    steps_per_epoch: -1
    save_every: 1

algo:
    type: MPPIIRLSpeedmaps
    params:
        mppi_itrs: 10
        batch_size: 12
        reg_coeff: 1.0e-08
        speed_coeff: 0.01
        grad_clip: 1.0

dataset:
    type: MaxEntIRLDataset
    params:
        bag_fp: /home/atv/Desktop/datasets/yamaha_maxent_irl/racer_perception_res/rosbags_train
        preprocess_fp: /home/atv/Desktop/datasets/yamaha_maxent_irl/racer_perception_res/torch_train_h75
        map_features_topic: /local_gridmap
        odom_topic: /integrated_to_init
        image_topic: /multisense/left/image_rect_color
        horizon: 75
        feature_keys:
            - height_low
            - height_mean
            - height_high
            - height_max
            - diff
            - terrain
            - terrain_slope
            - roughness
            - SVD1
            - SVD2
            - SVD3
            - unknown

network:
    type: ResnetCostmapSpeedmapCNNEnsemble2
    params:
        ensemble_dim: 8
        hidden_channels: [128]
        hidden_activation: elu
        activation_type: none
        activation_scale: 1.0
        dropout: 0.2

netopt:
    type: AdamW
    params: {}

cost_function:
    terms:
        - type: SwathedCostmapProjection
          weight: 1.0
          params:
              xs: [-2.3622, 1.6002, 7]
              ys: [-0.7620, 0.7620, 5]

        - type: EuclideanDistanceToGoal
          weight: 10.0
          params:

model:
    type: SteerSetpointKBM
    params:
        L: 3.0
        v_target_lim: [2.0, 15.0]
        steer_lim: [-0.5, 0.5]
        steer_rate_lim: 0.5
        v_Kp: 1.0
        w_Kp: 10.0

trajopt:
    type: BatchMPPI
    params: 
        num_samples: 2048
        control_params:
            sys_noise: [5.0, 0.25]
            temperature: 0.1
            use_ou: True
            ou_alpha: 0.9
            ou_scale: 10.0
            d_ou_scale: 2.0

metrics:
