experiment:
    save_to: /home/atv/Desktop/experiments/warthog_maxent_irl
    name: linear_highspeed_both
    device: cuda
    epochs: 10
    steps_per_epoch: -1
    save_every: 1

algo:
    type: MPPIIRLSpeedmaps
    params:
        mppi_itrs: 10
        batch_size: 12
        reg_coeff: 1.0e-08
        speed_coeff: 0.0
        grad_clip: 1.0

dataset:
    type: MaxEntIRLDataset
    params:
        bag_fp: /home/atv/Desktop/datasets/warthog_irl/rosbags_train_high_speed
        preprocess_fp: /home/atv/Desktop/datasets/warthog_irl/torch_train_high_speed
        map_features_topic: /local_gridmap
        odom_topic: /integrated_to_init
        image_topic: /warty/stereo_left/image_rect_color/compressed
        horizon: 75
        dt: 0.25
        feature_keys:
            - height_low
            - height_mean
            - height_high
            - height_max
            - diff
            - terrain
            - terrain_slope
            - roughness
            - SVD1
            - SVD2
            - SVD3
            - unknown
            - semantic_unknown
            - semantic_label_2 #trail
            - semantic_label_3 #grass
            - semantic_label_4 #low veg
            - semantic_label_5 #high veg
            - semantic_label_6 #obstacle

network:
    type: LinearCostmapSpeedmapEnsemble2
    params:
        ensemble_dim: 8
        activation_type: none
        activation_scale: 1.0
        dropout: 0.0

netopt:
    type: AdamW
    params: {}

cost_function:
    terms:
        - type: CostmapProjection
          weight: 1.0
          params:

        - type: EuclideanDistanceToGoal
          weight: 50.0
          params:

model:
    type: SkidSteer
    params:
        v_lim: [0.0, 5.0]
        w_lim: [-1.0, 1.0]

trajopt:
    type: BatchMPPI
    params: 
        num_samples: 2048
        num_safe_timesteps: 0
        control_params:
            sys_noise: [2.0, 0.4]
            temperature: 0.04
            use_ou: True
            ou_alpha: 0.9
            ou_scale: 10.0
            d_ou_scale: 5.0

metrics:
