experiment:
    save_to: /home/atv/Desktop/experiments/warthog_maxent_irl
    name: resnet_local_perception_uw
    device: cuda
    epochs: 10
    steps_per_epoch: -1
    save_every: 1

algo:
    type: MPPIIRLSpeedmaps
    params:
        mppi_itrs: 10
        batch_size: 12
        reg_coeff: 1.0e-08
        speed_coeff: 0.0
        grad_clip: 1.0

dataset:
    type: MaxEntIRLDataset
    params:
        bag_fp: /home/atv/Desktop/datasets/warthog_irl/rosbags_local_perception_uw
        preprocess_fp: /home/atv/Desktop/datasets/warthog_irl/torch_train_uw
        map_features_topic: /local_gridmap
        odom_topic: /warty/odom
        image_topic: /warty/stereo_left/image_rect_color/compressed
        horizon: 75
        dt: 0.25
        feature_keys:
            - height_low
            - height_mean
            - height_high
            - height_max
            - diff
            - terrain
            - terrain_slope
            - roughness
            - SVD1
            - SVD2
            - SVD3
            - unknown
            - npts
            - log_npts

network:
    type: ResnetCostmapSpeedmapCNNEnsemble2
    params:
        ensemble_dim: 8
        hidden_channels: [128]
        hidden_activation: elu
        activation_type: none
        activation_scale: 1.0
        dropout: 0.0

netopt:
    type: AdamW
    params: {}

cost_function:
    terms:
        - type: CostmapProjection
          weight: 1.0
          params:

        - type: EuclideanDistanceToGoal
          weight: 10.0
          params:

model:
    type: SkidSteer
    params:
        v_lim: [0.0, 3.0]
        w_lim: [-1.0, 1.0]

#model:
#    type: SteerSetpointKBM
#    params:
#        L: 1.0
#        v_target_lim: [0.0, 4.0]
#        steer_lim: [-1.0, 1.0]
#        steer_rate_lim: 1.0
#        v_Kp: 10.0
#        w_Kp: 10.0

trajopt:
    type: BatchMPPI
    params: 
        num_samples: 2048
        num_safe_timesteps: 0
        control_params:
            sys_noise: [1.5, 1.0]
            temperature: 0.04
            use_ou: True
            ou_alpha: 0.9
            ou_scale: 10.0
            d_ou_scale: 5.0

metrics:
