experiment:
    save_to: /home/atv/Desktop/experiments/wild_places_irl/
    name: 1layer_resnet
    device: cuda
    epochs: 10
    steps_per_epoch: -1
    save_every: 1

algo:
    type: MPPIIRLSpeedmaps
    params:
        mppi_itrs: 10
        batch_size: 12
        reg_coeff: 1.0e-08
        speed_coeff: 0.01
        grad_clip: 1.0

dataset:
    type: MaxEntIRLDataset
    params:
        bag_fp: /home/atv/Desktop/datasets/wild_places_irl/rosbags_train
        preprocess_fp: /home/atv/Desktop/datasets/wild_places_irl/torch_train
        map_features_topic: /local_gridmap
        odom_topic: /integrated_to_init
        horizon: 150
        feature_keys:
            - height_low
            - height_mean
            - height_high
            - height_max
            - diff
            - terrain
            - terrain_slope
            - roughness
            - SVD1
            - SVD2
            - SVD3
            - unknown

network:
    type: ResnetCostmapSpeedmapCNNEnsemble2
    params:
        ensemble_dim: 16
        hidden_channels: [128]
        hidden_activation: relu
        activation_type: none
        activation_scale: 1.0
        dropout: 0.0

netopt:
    type: AdamW
    params: {}

cost_function:
    terms:
        - type: CostmapProjection
          weight: 1.0
          params:

        - type: EuclideanDistanceToGoal
          weight: 100.0
          params:

model:
    type: KinematicPointMass
    params:
        v_lim: [-2.0, 2.0]

trajopt:
    type: BatchMPPI
    params: 
        num_samples: 2048
        control_params:
            sys_noise: [0.2, 0.2]
            temperature: 0.1
            use_ou: True
            ou_alpha: 0.9
            ou_scale: 10.0
            d_ou_scale: 5.0

metrics:
